### ISSUE TITLE
Try to update: Git pull && NPM install aborting because of package-lock.json

### ISSUE THREAD

**Issue by MadhunterNL** [paviro/MMM-PIR-Sensor#106]
When I try to git pull I get this error:

The following untracked working tree files would be overwritten by merge:
        package-lock.json
Please move or remove them before you merge.
Aborting

How can I avoid this error? I get this not only with this module but also with other module updates.

**Comment by M1dn8** [comment]
cd MagicMirror/modules/MMM-PIR-Sensor
rm package-lock.json
git pull

this was my solution!

**Comment by paviro** [comment]
I am not sure https://github.com/paviro/MMM-PIR-Sensor/blob/master/package-lock.json should be in the repo any insight @eric-h-st? Besides that I am unsure if remove the file is avoidable since it is generated on 'npm install' I think.

**Comment by eric-h-st** [comment]
Please do a `git pull`. The said file has been removed.
