### ISSUE TITLE
user_presence<>poweroffdelay

### ISSUE THREAD

**Issue by ksdehoff** [paviro/MMM-PIR-Sensor#107]
Hello:

I'd like to delay the mirror shutting down by 60 seconds.  I'm using a microwave motion detector that is very sensitive and does not have any configurable delay.

The problem I'm having is that as soon as the motion detector changes to 'no motion', the user_presence flag is set.  This is causing my camera monitoring to turn off immediately - mmm-rtspstream shuts the streams off immediately on having user_presence flag set to no presence.

Is there a way to either delay the user_presence by the poweroffdisplay value or create a 2nd user_presence delay?

Thanks

**Comment by eric-h-st** [comment]
The module reflects the actual presence, as detected, and is not the only one emitting USER_PRESENCE, thus any change here will not affect the other modules. 
As an immediate remedy for such a special case I would suggest using [MMM-NotificationTrigger](https://github.com/eouia/MMM-NotificationTrigger), setting it in the config above (before) the MMM-RTSPSTREAM, catching the USER_PRESENCE OFF notification, emitting an immediate USER_PRESENCE ON notification and adding a timer to emit another USER_PRESENCE OFF notification.

This way, the OFF and ON messages will come one after the other, thus the camera will be paused and resumed within less than a second, none-noticeably, and you'd control when you really want to emit the USER_PRESENCE OFF notification, after your own delay. 

Hope this helps. 

Eric
