### ISSUE TITLE
After Installation, version error

### ISSUE THREAD

**Issue by KilleKat** [paviro/MMM-PIR-Sensor#2]
Hey,

I want to use this module. After I go through your installation steps. I only see a black screen on the mirror and nothing happens. Also the console show a version error (see screenshot)

![magic bug](https://cloud.githubusercontent.com/assets/19373078/15274574/9e3efd2c-1ab5-11e6-8eab-fb11a3ec921f.png)

Unfortunatelly I am not a NodeJS or npm expert,... so maybe I have done something wrong.

**Comment by paviro** [comment]
Please use Node v5 not v6 since it is not compatible yet.

**Comment by KilleKat** [comment]
How I do this? How can i downgrade?

**Comment by paviro** [comment]
http://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js :)

**Comment by KilleKat** [comment]
I have downgrade, but still get this issue :(
![bug2](https://cloud.githubusercontent.com/assets/19373078/15274632/70d39314-1ab7-11e6-9cd2-34f2408eb2b7.png)

**Comment by paviro** [comment]
Run npm install again.

**Comment by KilleKat** [comment]
In which folder I have to run 'sudo npm install' ? I have done it in the 'MMM-PIR-Sensor' and in the 'MagicMirror' folder but I still get the verison issue

**Comment by paviro** [comment]
What das node -v say?

**Comment by KilleKat** [comment]
pi@raspberrypi:~ $ node -v
v5.11.1
pi@raspberrypi:~ $

**Comment by paviro** [comment]
try removing the module folder and loading it from git again.

**Comment by KilleKat** [comment]
Now it s working fine!!! Yeah, thx! Can you maybe send me a picture how you have setup your PIR sensor?
