### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by ssynix** [paviro/MMM-PIR-Sensor#21]
The behavior that I see with this module is my monitor constantly flashing on and off when the sensor detects any movement, and instantly turns off when no motion is detected.

I modified the source code to include a 20 sec timer. If there's any motion detected, the timer is reset. The monitor turns off once the timer goes off. This resulted in the kind of behavior I was expecting.

I'm wondering if there's something wrong with my setup or sensor which is resulting in the former behavior.

**Comment by Strychy** [comment]
Hey ssynix would you be willing to share the modifications you have made to the code? I'm also experiencing this issue.

**Comment by Patrick-Remy** [comment]
For additional software-side delay see my PR #20

**Comment by KX900** [comment]
@ssynix 
could you share, how to add the timer?

**Comment by ssynix** [comment]
Sorry, I was busy with work. I put it up on my fork: https://github.com/ssynix/MMM-PIR-Sensor

**Comment by paviro** [comment]
Will probably be merged soon :)
