### ISSUE TITLE
How to use sensor

### ISSUE THREAD

**Issue by SamLewis0602** [paviro/MMM-PIR-Sensor#3]
Could you give some insight into how to connect the sensor to the pi? I see that the pins labeled 22 on the bottom of the pi have 2 pins, but then there are 3 on the sensor for ground, output, and power. I have zero experience with hardware stuff so I'm not sure which 2 should be used and which pins they should be connected to on the pi. Thank you!

**Comment by paviro** [comment]
The issues on GitHub are for bugs :) if you need help check out the forum at http://forum.magicmirror.builders

**Comment by SamLewis0602** [comment]
Sorry about that, it didn't seem like the right place to post but I wasn't sure where to go! Thanks for the link.
