### ISSUE TITLE
Adding delay option

### ISSUE THREAD

**Issue by skoupayou** [paviro/MMM-PIR-Sensor#5]
Hi there,
at the moment I didn't went trought the code, I just install and configure it, wich works perfeclty.
Anyway I just wonder if it's simple to implement a delay option to keep monitor ON during a configurable amount of time.
Just to allow it switching on and off all time ;)

**Comment by paviro** [comment]
See on [forum](https://forum.magicmirror.builders/topic/52/pir-sensor-put-your-mirror-to-sleep-if-not-used/26).
