### ISSUE TITLE
Struggling to get it to work.

### ISSUE THREAD

**Issue by qwertyjon** [paviro/MMM-PIR-Sensor#59]
I had this module working with the last version of MM, since that updated, it threw in a few niggles for me to sort out, then after your update it doesn't seem to work anymore. 

I can get the status of the screen using `vcgencmd display_power`, 
and can turn it on and off manually in the CLI using the command lines
`vcgencmd display_power 1`
`vcgencmd display_power 0`

I also have a python script showing that the PIR is working.

It just doesn't all seem to talk to each other. 

I've tried removing it, and re-installing - any ideas???

**Update**: Tried the fixes in #49 and #54 - issue has changed and now is screen is black when MM starts, HDMI is still turned on.

**Update**: I've managed to get MM displaying again, it was an OpenGL issue, not yours. pm2 logs still not showing any errors though

**Comment by ReD1470** [comment]
Hi there

i also have troubles getting it to work. when i add the module to the config. the screen goes blank after 10 or so seconds, and after 10 or so seconds turns back on again
. pls let me know what info you need from me, to help troubleshoot the issue
 
kind regards John
