### ISSUE TITLE
Why a bright line is displayed on the screen

### ISSUE THREAD

**Issue by xdker** [paviro/MMM-PIR-Sensor#6]
Hello, I have a problem.
When a sensor is triggered, a line is displayed on the screen, and how to deal with the problem.
![qq 20160701134131](https://cloud.githubusercontent.com/assets/13342484/16512861/4b252074-3f92-11e6-94dd-dbcdbeca9ca2.jpg)
Sorry, my English is poor.

**Comment by paviro** [comment]
No idea how the module could cause this! Maybe it is some electrical interference?
