### ISSUE TITLE
After some time monitor wakes up but screen is blask

### ISSUE THREAD

**Issue by Goggite** [paviro/MMM-PIR-Sensor#67]
Hello!
Modul is perfectly working, monitor goes to sleep and wakes up if motion detected.
But after some time (may be 10-15 hours) I see that after motion detected monitor wakes up, but screen is black. At the same time I can reach system by SSH. Looks like system is in sleep mode even HDMI signal is presented.
After rebooting all is working but 10-15 hours.
Hardware: Raspberry PI 3, LG Monitor
Software: Latest MagicMirror

Please help me with this issue.

**Comment by Skorpionbird** [comment]
I have the same Issue

**Comment by Goggite** [comment]
Skorpionbird, I have solved the problem.
Just install WatchDog module (https://github.com/MichMich/MMM-WatchDog).
All is perfectly working now.
