### ISSUE TITLE
Is there a way to leave the monitor on for x minutes when movement is detected?

### ISSUE THREAD

**Issue by atoaster** [paviro/MMM-PIR-Sensor#8]
First off, awesome module, I think it is definitely my favourite one thus far!

I've found that most sensors are more sensitive to movement rather than actual presence. If someone stands still in front of the sensor, it will detect  0 after a few seconds. Is there a way to leave the monitor on for a few minutes, and if no movement is detected then turn the monitor off?

I have the idea out in pseudocode but am not certain how to implement it myself:

`if (relayOnState == 0 && timer > 300){
      turn_monitor_off();
} else if (relayOnState == 1) {
      timer.reset();
      turn_monitor_on();
}`

Thanks heaps :)

**Comment by paviro** [comment]
I haven't implemented that because my sensor can do it in hardware, if you would like to add it as an optional (default to disabled) feel free to send a pull request! You can get help at the development section at http://forum.magicmirror.builders :)
