### ISSUE TITLE
2 things are missing in this Git

### ISSUE THREAD

**Issue by Bibelo** [paviro/MMM-PIR-Sensor#85]
Hello

I wanted a quick way to do the PIR thing,

But missing an example config. Could deal with that but still could be clearer.

And more importantly, missing a way to debug see logs. pm2 logs shows nothing.

**Comment by idem2lyon** [comment]
I'm agree... no example

**Comment by eric-h-st** [comment]
@Bibelo Please see example config in the latest `git pull`
