### ISSUE TITLE
Electron version number unable to find 

### ISSUE THREAD

**Issue by haliszebi** [paviro/MMM-PIR-Sensor#90]
Hi!
I'm totally new to the Raspberry Pi (I have the Pi 3 model B+) and I've got a problem with this module. It shows nothing just black screen when it tries to run MagicMirror after I included the config to config.js. I've seen a comment where the guy said that he npm installed the PIR-Sensor in the directory.. So i've tried it and i've got an ERROR message which I attached. 
![2020-02-18-171747_1920x1080_scrot](https://user-images.githubusercontent.com/61199736/74755103-ecc05b00-5272-11ea-8e69-b9c09dafdfbe.png)

**Comment by andersarstrand** [comment]
Similar problem after updating MagicMirror to 2.11.0 .

My solution was :
Go to the module folder (cd modules/MMM-PIR-Sensor )
Reset GIT (git reset --hard) 
Remove the "node_modules" folder 
Reinstall the module (npm install)

**Comment by txuma2** [comment]
Same problem but has not been solved when doing the indicated operation
Any ideas?

**Comment by txuma2** [comment]
![pi](https://user-images.githubusercontent.com/65127257/81505470-a6b5e900-92ef-11ea-8a72-718080e5162a.png)

**Comment by Coumodo** [comment]
![image](https://user-images.githubusercontent.com/17899826/148061480-193f8218-b874-4b71-b3d6-85cab23242d6.png)

seems to be the same/compareable issue - git reset and also complete new MM installation didn't worked.
