### ISSUE TITLE
Thanks you for your great work !

### ISSUE THREAD

**Issue by pandeyprakhar00** [paviro/MMM-PIR-Sensor#92]
@paviro 

Thank you for building this module, which allowed me to build my own version of Magic Mirror !

https://www.youtube.com/watch?v=sCetiJk2Qus&list=PLBy3Sw0lBrNeihCn0fOr-m5RYJNb4w4IS

🥇

**Comment by eric-h-st** [comment]
@paviro I join the thanks!

**Comment by paviro** [comment]
@eric-h-st thank you for continuing maintaining it. I always had a lot of fun writing modules but I don’t really have the resources at the moment :/
