### ISSUE TITLE
How to launch magicmirror by default with monitor off

### ISSUE THREAD

**Issue by xplod609** [paviro/MMM-PIR-Sensor#96]
Hello,
Right now I have my raspberry pi reboot every morning at 2 am. 
After reboot the magicmirror launches but the monitor stays on without a counter. 
Only after motion is detected, the counter appears and the monitor turns off after 5 minutes. 
I have tried calling the deactivateMonitor: function () within node helper or even tried tricking the modules to think there is motion on the startup.
Any assistance.? 

PI reboots as once in a blue moon wifi drops and/or magicmirror might crash.

thank you

**Comment by eric-h-st** [comment]
Hi,

My latest PR solves the problem by starting the inactivity timer when application starts even if the PIR did not yet recognize any motion. I'd love a review :-) [](https://github.com/paviro/MMM-PIR-Sensor/pull/97)

Also, I think this thread would give you the info you're looking for: [](https://github.com/raspberrypi/userland/issues/447).
