### ISSUE TITLE
LOOKING FOR MAINTAINER

### ISSUE THREAD

**Issue by paviro** [paviro/MMM-PIR-Sensor#98]
Hi everyone,
As you probably noticed I don't have time to maintain this plugin at the moment. Is anyone interested in maintaining it? If yes I would be willing to give write access to the repo so existing pull requests can finally be merged.

Best,
Paul

**Comment by eric-h-st** [comment]
I'm up for it, if you want

**Comment by paviro** [comment]
Thank you!
